sets.exported={
    main="Nibiru Blade",
    sub="Ochain",
    ammo="Hydrocera",
    head="Flam. Zucchetto +1",
    body="Vatic Byrnie",
    hands="Flam. Manopolas +1",
    legs="Flamma Dirs +1",
    feet="Flam. Gambieras +1",
    neck="Fotia Gorget",
    waist="Fotia Belt",
    left_ear="Steelflash Earring",
    right_ear="Ishvara Earring",
    left_ring="Petrov Ring",
    right_ring="Rajas Ring",
    back="Atheling Mantle",
}